project13/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manoj1/',manoj1,name='manoj1'),
    path('venky/',venky,name='venky'),
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path

app_name='thinking'

urlpatterns=[
    path('brahma/',brahma,name='brahma'),
    path('bhuvi/',bhuvi,name='bhuvi'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def manoj1(request):
    return render(request,'manoj1.html')

def venky(request):
    return render(request,'venky.html')

specific/views.py
from django.shortcuts import render

# Create your views here.

def brahma(request):
    return render(request,'brahma.html')


def bhuvi(request):
    return render(request,'bhuvi.html')

templates/bhuvi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i'm Bhuneswar</h1>
        <h1>i'm from kavali</h1>
    </center>
</body>
</html>

templates/brahma.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i'm brahma</h1>
        <h1>i'm study for python full stack</h1>
    </center>
</body>
</html>

templates/manoj1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i'm Manoj kumar</h1>
        <h1>i'm from Nellore</h1>
        <a href="{% url 'venky' %}"><h1>click to venky</h1></a>
        <a href="{% url 'thinking:brahma' %}"><h1>click to brahma</h1></a>
    </center>
</body>
</html>

templates/venky.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i'm Venkatesh</h1>
        <h1>i'm from kavali</h1>
    </center>
</body>
</html>